//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElcheEventManager.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intersection
    {
        public int id { get; set; }
        public string primary_street { get; set; }
        public string secondary_street { get; set; }
        public int quantity { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public int material_id { get; set; }
        public int event_id { get; set; }
        public Nullable<int> position { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Material Material { get; set; }
    }
}
