//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElcheEventManager.Models.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Intersection
    {
        public int id { get; set; }
        [Display(Name = "Calle principal")]
        public string primary_street { get; set; }
        [Display(Name = "Calle secundaria")]
        public string secondary_street { get; set; }
        [Display(Name = "Cantidad")]
        [Range(0, int.MaxValue, ErrorMessage = "La cantidad debe ser un número no negativo")]
        public int quantity { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        [Display(Name = "Material")]
        public int material_id { get; set; }
        public int event_id { get; set; }
        public Nullable<int> position { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Material Material { get; set; }
    }
}
